version: "3"
services:

  postgres:
    image: postgres:15
    restart: on-failure
    env_file:
      - db.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ai-service:
    image: dbmgai:1.3
    restart: on-failure
    ports:
      - "8005:8080"